name: Upload Image to PocketBase

on:
  push:
    branches:
      - pocketbase-action
  workflow_dispatch:

jobs:
  upload-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Log Environment Variables
      run: |
        echo "PB_DOMAIN: $PB_DOMAIN"
        echo "PB_EMAIL: $PB_EMAIL"
      env:
        PB_DOMAIN: ${{ secrets.PB_DOMAIN }}
        PB_EMAIL: ${{ secrets.PB_EMAIL }}

    - name: Run uploadImageToPB
      run: node -e "require('./public/script/pocketbase.js').uploadImageToPB()"
      env:
        PB_DOMAIN: ${{ secrets.PB_DOMAIN }}
        PB_EMAIL: ${{ secrets.PB_EMAIL }}
        PB_PASSWORD: ${{ secrets.PB_PASSWORD }}
